#ifndef __COMMEN_VAR
#define __COMMEN_VAR

typedef enum{
	DAC_INIT_ERROR,
	DAC_CONFIG_ERROR,
	DMA_INIT_ERROR,
	DMA_START_ERROR,
	TIMER_INIT_ERROR,
	TIMER_CONFIG_ERROR,
	TIMER_START_ERROR,
	UART_INIT_ERROR,
	UART_TX_ERROR,
	UART_RX_ERROR,
	UART_INVALID_LABEL,
	FLASH_ERASE_ERROR,
	FLASH_ADDR_ERROR
}Error_Code;

typedef enum{
	OFF,
	ON
}Flag_Sig;

#define TIMEOUT 2000
#define PI 3.14159265
#define ACC_FREQ 25
#define UART_PERIOD 10
#define DAC_PERIOD 0.01
#define BUFFER_SIZE ACC_FREQ*UART_PERIOD

#endif
